from PyQt5 import QtCore, QtGui, QtWidgets
import sys, icons_rc

class Ui_MainWindow():
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(699, 418)
        MainWindow.setStyleSheet("\n"
"*{\n"
"    color: rgb(255, 255, 255);\n"
"border: none;\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        self.header_frame.setStyleSheet("background-color: rgb(82, 88, 105);")
        self.header_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.header_left_frame = QtWidgets.QFrame(self.header_frame)
        self.header_left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_left_frame.setObjectName("header_left_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.header_left_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.header_left_frame)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/outline_format_align_left_white_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.header_left_frame)
        self.header_center_frame = QtWidgets.QFrame(self.header_frame)
        self.header_center_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_center_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_center_frame.setObjectName("header_center_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.header_center_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.header_center_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/icons/outline_airplay_white_24dp.png"))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignRight)
        self.label_2 = QtWidgets.QLabel(self.header_center_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.horizontalLayout.addWidget(self.header_center_frame)
        self.header_right_frame = QtWidgets.QFrame(self.header_frame)
        self.header_right_frame.setStyleSheet("")
        self.header_right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_right_frame.setObjectName("header_right_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_right_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimize_window_button = QtWidgets.QPushButton(self.header_right_frame)
        self.minimize_window_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/outline_minimize_white_24dp2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_window_button.setIcon(icon1)
        self.minimize_window_button.setIconSize(QtCore.QSize(32, 32))
        self.minimize_window_button.setObjectName("minimize_window_button")
        self.horizontalLayout_2.addWidget(self.minimize_window_button)
        self.restore_window_button = QtWidgets.QPushButton(self.header_right_frame)
        self.restore_window_button.setStyleSheet("")
        self.restore_window_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/outline_cached_white_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restore_window_button.setIcon(icon2)
        self.restore_window_button.setIconSize(QtCore.QSize(32, 32))
        self.restore_window_button.setObjectName("restore_window_button")
        self.horizontalLayout_2.addWidget(self.restore_window_button)
        self.close_window_button = QtWidgets.QPushButton(self.header_right_frame)
        self.close_window_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/outline_close_white_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_window_button.setIcon(icon3)
        self.close_window_button.setIconSize(QtCore.QSize(32, 32))
        self.close_window_button.setObjectName("close_window_button")
        self.horizontalLayout_2.addWidget(self.close_window_button)
        self.horizontalLayout.addWidget(self.header_right_frame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.header_frame, 0, QtCore.Qt.AlignTop)
        self.main_body_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body_frame.sizePolicy().hasHeightForWidth())
        self.main_body_frame.setSizePolicy(sizePolicy)
        self.main_body_frame.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.main_body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body_frame.setObjectName("main_body_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.main_body_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.left_menu_cont_frame = QtWidgets.QFrame(self.main_body_frame)
        self.left_menu_cont_frame.setMinimumSize(QtCore.QSize(40, 0))
        self.left_menu_cont_frame.setMaximumSize(QtCore.QSize(20, 16777215))
        self.left_menu_cont_frame.setStyleSheet("background-color: rgb(82, 88, 105);\n"
"color: rgb(255, 255, 255);")
        self.left_menu_cont_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_cont_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_cont_frame.setObjectName("left_menu_cont_frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.left_menu_cont_frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.menu_frame = QtWidgets.QFrame(self.left_menu_cont_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_frame.sizePolicy().hasHeightForWidth())
        self.menu_frame.setSizePolicy(sizePolicy)
        self.menu_frame.setMinimumSize(QtCore.QSize(100, 0))
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.menu_frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.system_info_page_btn = QtWidgets.QPushButton(self.menu_frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.system_info_page_btn.setFont(font)
        self.system_info_page_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/outline_airplay_white_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.system_info_page_btn.setIcon(icon4)
        self.system_info_page_btn.setIconSize(QtCore.QSize(32, 32))
        self.system_info_page_btn.setObjectName("system_info_page_btn")
        self.gridLayout.addWidget(self.system_info_page_btn, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.sensors_page_btn = QtWidgets.QPushButton(self.menu_frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.sensors_page_btn.setFont(font)
        self.sensors_page_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/outline_thermostat_white_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sensors_page_btn.setIcon(icon5)
        self.sensors_page_btn.setIconSize(QtCore.QSize(32, 32))
        self.sensors_page_btn.setObjectName("sensors_page_btn")
        self.gridLayout.addWidget(self.sensors_page_btn, 5, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.cpu_page_btn = QtWidgets.QPushButton(self.menu_frame)
        self.cpu_page_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/outline_memory_white_24dp2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cpu_page_btn.setIcon(icon6)
        self.cpu_page_btn.setIconSize(QtCore.QSize(32, 32))
        self.cpu_page_btn.setObjectName("cpu_page_btn")
        self.gridLayout.addWidget(self.cpu_page_btn, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.batery_page_btn = QtWidgets.QPushButton(self.menu_frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.batery_page_btn.setFont(font)
        self.batery_page_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/outline_bolt_white_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.batery_page_btn.setIcon(icon7)
        self.batery_page_btn.setIconSize(QtCore.QSize(32, 32))
        self.batery_page_btn.setObjectName("batery_page_btn")
        self.gridLayout.addWidget(self.batery_page_btn, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.storage_btn = QtWidgets.QPushButton(self.menu_frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.storage_btn.setFont(font)
        self.storage_btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/outline_adjust_white_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.storage_btn.setIcon(icon8)
        self.storage_btn.setIconSize(QtCore.QSize(32, 32))
        self.storage_btn.setObjectName("storage_btn")
        self.gridLayout.addWidget(self.storage_btn, 4, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.activity_btn = QtWidgets.QPushButton(self.menu_frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.activity_btn.setFont(font)
        self.activity_btn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/outline_auto_graph_white_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.activity_btn.setIcon(icon9)
        self.activity_btn.setIconSize(QtCore.QSize(32, 32))
        self.activity_btn.setObjectName("activity_btn")
        self.gridLayout.addWidget(self.activity_btn, 3, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.networks_page_button = QtWidgets.QPushButton(self.menu_frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.networks_page_button.setFont(font)
        self.networks_page_button.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/outline_wifi_white_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.networks_page_button.setIcon(icon10)
        self.networks_page_button.setIconSize(QtCore.QSize(32, 32))
        self.networks_page_button.setObjectName("networks_page_button")
        self.gridLayout.addWidget(self.networks_page_button, 6, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.label_5 = QtWidgets.QLabel(self.menu_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.label_4 = QtWidgets.QLabel(self.menu_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.label_6 = QtWidgets.QLabel(self.menu_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.label_7 = QtWidgets.QLabel(self.menu_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.label_8 = QtWidgets.QLabel(self.menu_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.label_9 = QtWidgets.QLabel(self.menu_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.label_10 = QtWidgets.QLabel(self.menu_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.horizontalLayout_8.addWidget(self.menu_frame, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.horizontalLayout_7.addWidget(self.left_menu_cont_frame)
        self.main_body_contents = QtWidgets.QFrame(self.main_body_frame)
        self.main_body_contents.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body_contents.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body_contents.setObjectName("main_body_contents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.main_body_contents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_body_contents)
        self.stackedWidget.setStyleSheet("color: rgb(203, 203, 203);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.cpu_and_memory = QtWidgets.QWidget()
        self.cpu_and_memory.setObjectName("cpu_and_memory")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.cpu_and_memory)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.cpu_info_frame = QtWidgets.QFrame(self.cpu_and_memory)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cpu_info_frame.setFont(font)
        self.cpu_info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cpu_info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cpu_info_frame.setObjectName("cpu_info_frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.cpu_info_frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_15 = QtWidgets.QLabel(self.cpu_info_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.cpu_info_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 0, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.cpu_info_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 1, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.cpu_info_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_5.addWidget(self.label_35, 1, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.cpu_info_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 2, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.cpu_info_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout_5.addWidget(self.label_37, 2, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.cpu_info_frame)
        self.ram_info_frame = QtWidgets.QFrame(self.cpu_and_memory)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ram_info_frame.setFont(font)
        self.ram_info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ram_info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ram_info_frame.setObjectName("ram_info_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.ram_info_frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_38 = QtWidgets.QLabel(self.ram_info_frame)
        self.label_38.setObjectName("label_38")
        self.gridLayout_6.addWidget(self.label_38, 0, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.ram_info_frame)
        self.label_39.setObjectName("label_39")
        self.gridLayout_6.addWidget(self.label_39, 0, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.ram_info_frame)
        self.label_40.setObjectName("label_40")
        self.gridLayout_6.addWidget(self.label_40, 1, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.ram_info_frame)
        self.label_41.setObjectName("label_41")
        self.gridLayout_6.addWidget(self.label_41, 1, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.ram_info_frame)
        self.label_42.setObjectName("label_42")
        self.gridLayout_6.addWidget(self.label_42, 2, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.ram_info_frame)
        self.label_43.setObjectName("label_43")
        self.gridLayout_6.addWidget(self.label_43, 2, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.ram_info_frame)
        self.label_44.setObjectName("label_44")
        self.gridLayout_6.addWidget(self.label_44, 3, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.ram_info_frame)
        self.label_45.setObjectName("label_45")
        self.gridLayout_6.addWidget(self.label_45, 3, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.ram_info_frame)
        self.label_46.setObjectName("label_46")
        self.gridLayout_6.addWidget(self.label_46, 4, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.ram_info_frame)
        self.label_47.setObjectName("label_47")
        self.gridLayout_6.addWidget(self.label_47, 4, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.ram_info_frame)
        self.stackedWidget.addWidget(self.cpu_and_memory)
        self.battery = QtWidgets.QWidget()
        self.battery.setStyleSheet("color: rgb(200, 200, 200);\n"
"")
        self.battery.setObjectName("battery")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.battery)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_48 = QtWidgets.QLabel(self.battery)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_9.addWidget(self.label_48, 0, QtCore.Qt.AlignBottom)
        self.frame_4 = QtWidgets.QFrame(self.battery)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_49 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_7.addWidget(self.label_49, 0, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.gridLayout_7.addWidget(self.label_53, 0, 1, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.gridLayout_7.addWidget(self.label_50, 1, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.gridLayout_7.addWidget(self.label_54, 1, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout_7.addWidget(self.label_51, 2, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.gridLayout_7.addWidget(self.label_55, 2, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout_7.addWidget(self.label_52, 3, 0, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout_7.addWidget(self.label_56, 3, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.battery)
        self.system_information = QtWidgets.QWidget()
        self.system_information.setObjectName("system_information")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.system_information)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame = QtWidgets.QFrame(self.system_information)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_60 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.gridLayout_8.addWidget(self.label_60, 3, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.gridLayout_8.addWidget(self.label_62, 2, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.gridLayout_8.addWidget(self.label_58, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.label_61 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.gridLayout_8.addWidget(self.label_61, 4, 0, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.gridLayout_8.addWidget(self.label_64, 4, 1, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.gridLayout_8.addWidget(self.label_67, 4, 2, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.gridLayout_8.addWidget(self.label_65, 2, 2, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.gridLayout_8.addWidget(self.label_57, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.label_66 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.gridLayout_8.addWidget(self.label_66, 3, 2, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.gridLayout_8.addWidget(self.label_63, 3, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.gridLayout_8.addWidget(self.label_59, 2, 0, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.gridLayout_8.addWidget(self.label_68, 2, 3, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.gridLayout_8.addWidget(self.label_69, 3, 3, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.gridLayout_8.addWidget(self.label_70, 4, 3, 1, 1)
        self.verticalLayout_10.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.stackedWidget.addWidget(self.system_information)
        self.activites = QtWidgets.QWidget()
        self.activites.setObjectName("activites")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.activites)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_2 = QtWidgets.QFrame(self.activites)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_71 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.horizontalLayout_9.addWidget(self.label_71)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_10.addWidget(self.lineEdit)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_6.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/outline_search_white_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon11)
        self.pushButton_6.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_10.addWidget(self.pushButton_6)
        self.horizontalLayout_9.addWidget(self.frame_6, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_11.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.activites)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_3)
        self.tableWidget.setStyleSheet("color: rgb(0, 255, 0);\n"
"background-color: rgb(48, 48, 48);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.verticalLayout_12.addWidget(self.tableWidget)
        self.verticalLayout_11.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.activites)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_5.setFont(font)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_11.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_11.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_11.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_11.addWidget(self.pushButton_10)
        self.verticalLayout_11.addWidget(self.frame_5, 0, QtCore.Qt.AlignBottom)
        self.stackedWidget.addWidget(self.activites)
        self.storage = QtWidgets.QWidget()
        self.storage.setObjectName("storage")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.storage)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_72 = QtWidgets.QLabel(self.storage)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.verticalLayout_13.addWidget(self.label_72)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.storage)
        self.tableWidget_2.setStyleSheet("color: rgb(0, 255, 30);")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(9)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        self.verticalLayout_13.addWidget(self.tableWidget_2)
        self.stackedWidget.addWidget(self.storage)
        self.sensors = QtWidgets.QWidget()
        self.sensors.setObjectName("sensors")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.sensors)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_73 = QtWidgets.QLabel(self.sensors)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.verticalLayout_14.addWidget(self.label_73)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.sensors)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setStyleSheet("color: rgb(0, 255, 0);")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(6)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        self.verticalLayout_14.addWidget(self.tableWidget_3)
        self.stackedWidget.addWidget(self.sensors)
        self.networks = QtWidgets.QWidget()
        self.networks.setObjectName("networks")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.networks)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea = QtWidgets.QScrollArea(self.networks)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 391, 448))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.scrollAreaWidgetContents.setFont(font)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_74 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_74.setFont(font)
        self.label_74.setObjectName("label_74")
        self.verticalLayout_16.addWidget(self.label_74)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.frame_7)
        self.tableWidget_4.setStyleSheet("color: rgb(0, 255, 0);")
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(5)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        self.verticalLayout_16.addWidget(self.tableWidget_4)
        self.verticalLayout_15.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_75 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.verticalLayout_17.addWidget(self.label_75)
        self.tableWidget_5 = QtWidgets.QTableWidget(self.frame_8)
        self.tableWidget_5.setStyleSheet("color: rgb(0, 255, 0);")
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(9)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(8, item)
        self.verticalLayout_17.addWidget(self.tableWidget_5)
        self.verticalLayout_15.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_76 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_76.setFont(font)
        self.label_76.setObjectName("label_76")
        self.verticalLayout_18.addWidget(self.label_76)
        self.tableWidget_6 = QtWidgets.QTableWidget(self.frame_9)
        self.tableWidget_6.setStyleSheet("color: rgb(0, 255, 0);")
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(6)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(5, item)
        self.verticalLayout_18.addWidget(self.tableWidget_6)
        self.verticalLayout_15.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_77 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.verticalLayout_19.addWidget(self.label_77)
        self.tableWidget_7 = QtWidgets.QTableWidget(self.frame_10)
        self.tableWidget_7.setStyleSheet("color: rgb(0, 255, 0);")
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(6)
        self.tableWidget_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(5, item)
        self.verticalLayout_19.addWidget(self.tableWidget_7)
        self.verticalLayout_15.addWidget(self.frame_10)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.networks)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.horizontalLayout_7.addWidget(self.main_body_contents)
        self.right_frame = QtWidgets.QFrame(self.main_body_frame)
        self.right_frame.setStyleSheet("background-color: rgb(82, 88, 105);")
        self.right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame.setObjectName("right_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.right_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.about_frame = QtWidgets.QFrame(self.right_frame)
        self.about_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.about_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.about_frame.setObjectName("about_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.about_frame)
        self.verticalLayout_4.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.about_top_frame = QtWidgets.QFrame(self.about_frame)
        self.about_top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.about_top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.about_top_frame.setObjectName("about_top_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.about_top_frame)
        self.verticalLayout_5.setContentsMargins(10, 0, 30, 0)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.about_top_frame)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_13 = QtWidgets.QLabel(self.about_top_frame)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(204, 204, 204);")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.verticalLayout_4.addWidget(self.about_top_frame, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.about_main_frame = QtWidgets.QFrame(self.about_frame)
        self.about_main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.about_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.about_main_frame.setObjectName("about_main_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.about_main_frame)
        self.gridLayout_2.setContentsMargins(20, 0, 50, 0)
        self.gridLayout_2.setHorizontalSpacing(50)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_16 = QtWidgets.QLabel(self.about_main_frame)
        font = QtGui.QFont()
        font.setFamily("Sakkal Majalla")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 2, 1, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_12 = QtWidgets.QLabel(self.about_main_frame)
        font = QtGui.QFont()
        font.setFamily("Sakkal Majalla")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 1, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_14 = QtWidgets.QLabel(self.about_main_frame)
        font = QtGui.QFont()
        font.setFamily("Sakkal Majalla")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 1, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pushButton_3 = QtWidgets.QPushButton(self.about_main_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/outline_subscriptions_white_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon12)
        self.pushButton_3.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pushButton_4 = QtWidgets.QPushButton(self.about_main_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/icons/outline_local_cafe_white_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon13)
        self.pushButton_4.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 1, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pushButton_5 = QtWidgets.QPushButton(self.about_main_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/icons/outline_payment_white_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon14)
        self.pushButton_5.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 2, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.verticalLayout_4.addWidget(self.about_main_frame, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.about_grid = QtWidgets.QFrame(self.about_frame)
        self.about_grid.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.about_grid.setFrameShadow(QtWidgets.QFrame.Raised)
        self.about_grid.setObjectName("about_grid")
        self.verticalLayout_4.addWidget(self.about_grid, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_3.addWidget(self.about_frame, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_7.addWidget(self.right_frame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.main_body_frame)
        self.footer_frame = QtWidgets.QFrame(self.centralwidget)
        self.footer_frame.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.footer_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_frame.setObjectName("footer_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.footer_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.footer_left_frame = QtWidgets.QFrame(self.footer_frame)
        self.footer_left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_left_frame.setObjectName("footer_left_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.footer_left_frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.footer_left_frame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_5.addWidget(self.footer_left_frame)
        self.footer_right_frame = QtWidgets.QFrame(self.footer_frame)
        self.footer_right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer_right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_right_frame.setObjectName("footer_right_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.footer_right_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.footer_right_frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_5.addWidget(self.footer_right_frame)
        self.size_grip = QtWidgets.QFrame(self.footer_frame)
        self.size_grip.setMinimumSize(QtCore.QSize(10, 10))
        self.size_grip.setMaximumSize(QtCore.QSize(10, 10))
        self.size_grip.setSizeIncrement(QtCore.QSize(10, 10))
        self.size_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.size_grip.setObjectName("size_grip")
        self.horizontalLayout_5.addWidget(self.size_grip, 0, QtCore.Qt.AlignBottom)
        self.footer_right_frame.raise_()
        self.size_grip.raise_()
        self.footer_left_frame.raise_()
        self.verticalLayout.addWidget(self.footer_frame, 0, QtCore.Qt.AlignBottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Menu"))
        self.label_2.setText(_translate("MainWindow", "PSUTIL MANAGER"))
        self.label_5.setText(_translate("MainWindow", "Battery"))
        self.label_4.setText(_translate("MainWindow", "CPU"))
        self.label_6.setText(_translate("MainWindow", "System Information"))
        self.label_7.setText(_translate("MainWindow", "Activity"))
        self.label_8.setText(_translate("MainWindow", "Storage"))
        self.label_9.setText(_translate("MainWindow", "Sensors"))
        self.label_10.setText(_translate("MainWindow", "Network"))
        self.label_15.setText(_translate("MainWindow", "CPU Count"))
        self.label_33.setText(_translate("MainWindow", "N/A"))
        self.label_34.setText(_translate("MainWindow", "CPU Per"))
        self.label_35.setText(_translate("MainWindow", "N/A"))
        self.label_36.setText(_translate("MainWindow", "CPU Main Core"))
        self.label_37.setText(_translate("MainWindow", "N/A"))
        self.label_38.setText(_translate("MainWindow", "Total RAM"))
        self.label_39.setText(_translate("MainWindow", "N/A"))
        self.label_40.setText(_translate("MainWindow", "Aviable RAM"))
        self.label_41.setText(_translate("MainWindow", "N/A"))
        self.label_42.setText(_translate("MainWindow", "Used RAM"))
        self.label_43.setText(_translate("MainWindow", "N/A"))
        self.label_44.setText(_translate("MainWindow", "Free RAM"))
        self.label_45.setText(_translate("MainWindow", "N/A"))
        self.label_46.setText(_translate("MainWindow", "RAM Usage"))
        self.label_47.setText(_translate("MainWindow", "N/A"))
        self.label_48.setText(_translate("MainWindow", "Battery Information"))
        self.label_49.setText(_translate("MainWindow", "Status"))
        self.label_53.setText(_translate("MainWindow", "N/A"))
        self.label_50.setText(_translate("MainWindow", "Charge"))
        self.label_54.setText(_translate("MainWindow", "N/A"))
        self.label_51.setText(_translate("MainWindow", "Time Left"))
        self.label_55.setText(_translate("MainWindow", "N/A"))
        self.label_52.setText(_translate("MainWindow", "Plugget In"))
        self.label_56.setText(_translate("MainWindow", "N/A"))
        self.label_60.setText(_translate("MainWindow", "Version"))
        self.label_62.setText(_translate("MainWindow", "N/A"))
        self.label_58.setText(_translate("MainWindow", "N/A"))
        self.label_61.setText(_translate("MainWindow", "System Date"))
        self.label_64.setText(_translate("MainWindow", "N/A"))
        self.label_67.setText(_translate("MainWindow", "System Time"))
        self.label_65.setText(_translate("MainWindow", "Processor"))
        self.label_57.setText(_translate("MainWindow", "System Information"))
        self.label_66.setText(_translate("MainWindow", "Machine"))
        self.label_63.setText(_translate("MainWindow", "N/A"))
        self.label_59.setText(_translate("MainWindow", "Platform"))
        self.label_68.setText(_translate("MainWindow", "N/A"))
        self.label_69.setText(_translate("MainWindow", "N/A"))
        self.label_70.setText(_translate("MainWindow", "N/A"))
        self.label_71.setText(_translate("MainWindow", "Activites"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search Processes"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Process ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Process Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Process Status"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Suspend"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Started"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Resume"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Terminate"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Kill"))
        self.pushButton_7.setText(_translate("MainWindow", "Suspend"))
        self.pushButton_8.setText(_translate("MainWindow", "Resume"))
        self.pushButton_9.setText(_translate("MainWindow", "Terminate"))
        self.pushButton_10.setText(_translate("MainWindow", "Kill"))
        self.label_72.setText(_translate("MainWindow", "Disk Partition"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Device"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mount Point"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "OPTS"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Max File"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Max Path"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Total Storage"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Used Storage"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Free Strorage"))
        self.label_73.setText(_translate("MainWindow", "Sensors"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sensor"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Новый столбец"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Current"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Новый столбец"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Critical"))
        self.label_74.setText(_translate("MainWindow", "Stats"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ISUP"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Duplex"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Speed"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "MTU"))
        self.label_75.setText(_translate("MainWindow", "Network IO Counter"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IO"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Bytes Sent"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Bytes Recevied"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Packets Sent"))
        item = self.tableWidget_5.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Packets Recevied"))
        item = self.tableWidget_5.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ERR In"))
        item = self.tableWidget_5.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "ERR Out"))
        item = self.tableWidget_5.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Drop In"))
        item = self.tableWidget_5.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Drop Out"))
        self.label_76.setText(_translate("MainWindow", "Network Addresses"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Family"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Address"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Netmask"))
        item = self.tableWidget_6.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Broadcast"))
        item = self.tableWidget_6.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "PTP"))
        self.label_77.setText(_translate("MainWindow", "Network Connections"))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "FD"))
        item = self.tableWidget_7.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Family"))
        item = self.tableWidget_7.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Family"))
        item = self.tableWidget_7.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "LADDR"))
        item = self.tableWidget_7.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "RADDR"))
        item = self.tableWidget_7.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "PID"))
        self.label_11.setText(_translate("MainWindow", "About"))
        self.label_13.setText(_translate("MainWindow", "App Designed And\n"
"Developed By ICT \n"
"Academy."))
        self.label_16.setText(_translate("MainWindow", "PayPal"))
        self.label_12.setText(_translate("MainWindow", "YouTube/"))
        self.label_14.setText(_translate("MainWindow", "Patreon/"))
        self.label_3.setText(_translate("MainWindow", "Version 1.0 | Copyright"))
        self.pushButton_2.setText(_translate("MainWindow", "?"))
# import icons_rc


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
    # MainWindow.show()
    # sys.exit(app.exec_())
